[id]
name = netkit
version = 1.0.0

[install]
state = enabled

[ui]
is_visible = 1
label = NetKit App

[launcher]
author = David Twersky
description = NetKit App. Dashboards for network latency and throughput trends, for use with Splunk Enterprise and Splunk Cloud. Companion to the NetKit Add-on.
version = 1.0.0

[package]
id = netkit
check_for_updates = 0
