[id]
name = netkit
version = 1.1.0

[install]
state = enabled

[ui]
is_visible = 1
label = NetKit App

[launcher]
author = David Twersky
description = NetKit App. Dashboards for network latency, throughput, and TLS certificate trends, for use with Splunk Enterprise and Splunk Cloud. Requires the NetKit Add-on (https://splunkbase.splunk.com/app/9165).
version = 1.1.0

[package]
id = netkit
check_for_updates = 0
